export interface GameItem {
  id: string
  title: string
  description: string
  controls?: string
  storyDescription?: string
  seoKeywords?: string[]
  occultTheme?: string
  thumbnail: string
  category: 'web_games' | 'simulation' | '3d_physics'
  icon: string
  path: string
  image?: string
  tags?: string[]
  play_count?: number
}

export const GAMES_DATA: GameItem[] = [
  {
    id: 'the-way-of-the-dodo',
    title: 'the-way-of-the-dodo',
    description: '🎮 Navigate a world where extinction holds secrets beyond death itself.',
    controls: "⌨️ [WASD] Move | [Space] Interact | 🖱️ [Click] Examine | [R] Meditate",
    storyDescription: "The dodo, declared extinct, whispers from beyond dimensional veils. Walking their path reveals that extinction is merely a transition to another plane of existence. Each step echoes through timestreams where the species never truly perished.",
    image: "/thumbnails/the-way-of-the-dodo.png",
    seoKeywords: ['extinction dimensional portal', 'dodo spirit simulator', 'temporal anomaly game', 'necromantic wildlife experience', 'interdimensional extinction guide'],
    occultTheme: 'necromancy-spirits',
    thumbnail: '💀',
    category: 'web_games',
    icon: '💀',
    path: '/game/the-way-of-the-dodo',
    tags: ['auto-classified', 'web_games', 'occult', 'extinction'],
    play_count: 0,
  },
  {
    id: 'sub13',
    title: 'sub13',
    description: '🎮 Descend into abyssal depths where submarine pressure warps reality.',
    controls: "⌨️ [WASD] Pilot Submarine | [Q/E] Depth Control | 🖱️ [Click] Sonar | [Space] Activate Shield",
    storyDescription: "Submarine 13 descends beyond known ocean depths where bioluminescent entities defy taxonomy. Signals from the abyss grow stronger as pressure itself becomes conscious. The deeper descent reveals infrastructure built by no known civilization.",
    image: "/thumbnails/sub13.png",
    seoKeywords: ['abyssal submarine explorer', 'deep ocean anomaly detector', 'bioluminescent entity simulator', 'pressure warping physics game', 'undiscovered species hunter'],
    occultTheme: 'abyssal-frequencies',
    thumbnail: '🔮',
    category: 'web_games',
    icon: '🔮',
    path: '/game/sub13',
    tags: ['auto-classified', 'web_games', 'exploration', 'mystery'],
    play_count: 0,
  },
  {
    id: 'squad-13',
    title: 'squad-13',
    description: '🎮 Command tactical operatives through dimensions that resist conventional physics.',
    controls: "⌨️ [WASD] Move Squad | [Q] Ability | 🖱️ [Click] Target | [Space] Regroup",
    storyDescription: "Squad 13 receives orders to navigate zones where physics laws fractionate into competing axioms. Each operative moves through simultaneously overlapping realities. Coordination breaks down at dimensional intersections where causality loops.",
    image: "/thumbnails/squad-13.png",
    seoKeywords: ['tactical anomaly warfare', 'dimensional squad simulator', 'fractioned physics combat', 'impossible formation tactics', 'reality-bending unit commands'],
    occultTheme: 'anomalous-physics',
    thumbnail: '⚡',
    category: 'web_games',
    icon: '⚡',
    path: '/game/squad-13',
    tags: ['auto-classified', 'web_games', 'action', 'tactical'],
    play_count: 0,
  },
  {
    id: 'six-and-seven',
    title: 'six-and-seven',
    description: '🎮 Sacred numbers dance through geometric dimensional frameworks.',
    controls: "🖱️ [Mouse] Arrange Numbers | [Space] Activate Pattern | [R] Reset",
    storyDescription: "Six and Seven are cosmic constants that govern dimensional lattices. Arranging them in sacred patterns unlocks pathways between worlds. Mathematical harmony becomes spiritual power when numbers align with cosmic geometry.",
    image: "/thumbnails/six-and-seven.png",
    seoKeywords: ['sacred number geometry', 'mathematical dimensional gateway', 'harmonic pattern puzzle', 'cosmic constant simulator', 'mystical mathematics game'],
    occultTheme: 'sacred-geometry',
    thumbnail: '✨',
    category: 'web_games',
    icon: '✨',
    path: '/game/six-and-seven',
    tags: ['auto-classified', 'web_games', 'puzzle', 'mystical'],
    play_count: 0,
  },
  {
    id: 'phantomicus',
    title: 'phantomicus',
    description: '🎮 Commune with spectral presences that exist between matter and void.',
    controls: "⌨️ [WASD] Phase Walk | 🖱️ [Click] Summon Spirit | [Space] Manifest",
    storyDescription: "Phantomicus teaches the language of ghosts—those caught between dimensions. Spectral entities whisper histories of civilizations that never solidified into timeline. Communication requires fragmenting your own consciousness across realities.",
    image: "/thumbnails/phantomicus.png",
    seoKeywords: ['phantom spirit communication', 'ghostly entity simulator', 'spectral presence detector', 'interdimensional linguist game', 'consciousness fragmentation portal'],
    occultTheme: 'necromancy-spirits',
    thumbnail: '💀',
    category: 'web_games',
    icon: '💀',
    path: '/game/phantomicus',
    tags: ['auto-classified', 'web_games', 'mystical', 'horror'],
    play_count: 0,
  },
  {
    id: 'ghosted',
    title: 'ghosted',
    description: '🎮 Navigate reality where romantic abandonment fractures consciousness itself.',
    controls: "⌨️ [WASD] Wander Through Illusions | 🖱️ [Click] Search Memories | [Space] Fade",
    storyDescription: "Being ghosted tears perception into fragments where absence becomes tangible. Exploring this psychological landscape reveals that abandonment creates dimensional tears. Each lost connection is a rift between realities where alternate timelines diverge.",
    image: "/thumbnails/ghosted.png",
    seoKeywords: ['psychological abandonment simulator', 'relationship trauma dimensional portal', 'memory fragmentation game', 'emotional void explorer', 'consciousness splinter experience'],
    occultTheme: 'illusions-hallucinations',
    thumbnail: '🎭',
    category: 'web_games',
    icon: '🎭',
    path: '/game/ghosted',
    tags: ['auto-classified', 'web_games', 'psychological', 'surreal'],
    play_count: 0,
  },
  {
    id: 'dr1v3n-wild',
    title: 'dr1v3n-wild',
    description: '🎮 Accelerate through landscapes where velocity rewrites physical laws.',
    controls: "⌨️ [WASD] Accelerate | [Space] Drift | 🖱️ [Click] Nitro Boost",
    storyDescription: "Dr1v3n pushes vehicles beyond speed limits where momentum itself becomes conscious. At critical velocities, the driver phases through barriers into alternate highway networks. High-speed travel becomes interdimensional navigation.",
    image: "/thumbnails/dr1v3n-wild.png",
    seoKeywords: ['velocity anomaly racer', 'momentum-bending physics game', 'interdimensional highway explorer', 'speed-induced dimensional portal', 'acceleration reality simulator'],
    occultTheme: 'anomalous-physics',
    thumbnail: '⚡',
    category: 'web_games',
    icon: '⚡',
    path: '/game/dr1v3n-wild',
    tags: ['auto-classified', 'web_games', 'action', 'racing'],
    play_count: 0,
  },
  {
    id: 'bubble-burst',
    title: 'bubble-burst',
    description: '🎮 Pop dimensional bubbles that contain fragments of compressed realities.',
    controls: "🖱️ [Mouse] Pop Bubbles | [Space] Cascade Burst | [E] Special Ability",
    storyDescription: "Each bubble holds a complete but compressed dimension. Bursting them releases reality shards that reshape the game space. Chain reactions of pops create dimensional cascades where multiple worlds momentarily intersect.",
    image: "/thumbnails/bubble-burst.png",
    seoKeywords: ['dimensional bubble physics', 'reality compression game', 'cascade dimensional rupture', 'geometric pop simulator', 'intersection space explorer'],
    occultTheme: 'sacred-geometry',
    thumbnail: '✨',
    category: 'web_games',
    icon: '✨',
    path: '/game/bubble-burst',
    tags: ['auto-classified', 'web_games', 'puzzle', 'casual'],
    play_count: 0,
  },
  {
    id: 'brewing-disaster',
    title: 'brewing-disaster',
    description: '🎮 Alchemically combine forbidden ingredients that defy atomic structure.',
    controls: "🖱️ [Click/Drag] Mix Ingredients | [Space] Ignite Reaction | [R] Reset Cauldron",
    storyDescription: "Brewing catastrophes requires ingredients from across dimensional boundaries—matter that shouldn't coexist. Each combination risks uncontrolled transmutation. The ideal disaster brews when elements achieve forbidden harmony.",
    image: "/thumbnails/brewing-disaster.png",
    seoKeywords: ['forbidden alchemy simulator', 'matter transmutation experiment', 'catastrophic reaction brewery', 'interdimensional ingredient mixer', 'alchemical disaster composer'],
    occultTheme: 'alchemy-dark-magic',
    thumbnail: '⚗️',
    category: 'web_games',
    icon: '⚗️',
    path: '/game/brewing-disaster',
    tags: ['auto-classified', 'web_games', 'alchemy', 'puzzle'],
    play_count: 0,
  },
  {
    id: 'aargh-triskaideka-attacks',
    title: 'aargh-triskaideka-attacks',
    description: '🎮 Defend against thirteen simultaneous anomalous assaults from the abyss.',
    controls: "⌨️ [WASD] Position | 🖱️ [Click] Defend | [Space] Counter | [Q] Ability",
    storyDescription: "Thirteen attacks synchronize from thirteen dimensions, each at critical angles. Defending requires calculating impossible trajectories. Each repelled assault opens new rifts where 13 more threats emerge. The number multiplies endlessly.",
    image: "/thumbnails/aargh-triskaideka-attacks.png",
    seoKeywords: ['unlucky number defense game', 'thirteen synchronized anomalies', 'abyssal assault simulator', 'dimensional coordinate warfare', 'impossible multiplication defense'],
    occultTheme: 'abyssal-frequencies',
    thumbnail: '🔮',
    category: 'web_games',
    icon: '🔮',
    path: '/game/aargh-triskaideka-attacks',
    tags: ['auto-classified', 'web_games', 'action', 'arcade'],
    play_count: 0,
  },
  {
    id: '13-steps-to-escape',
    title: '13-steps-to-escape',
    description: '🎮 Climb thirteen stages of dimensional barriers to reach the outside.',
    controls: "⌨️ [WASD] Climb | [Space] Jump | 🖱️ [Click] Activate Portal | [R] Reset",
    storyDescription: "Thirteen steps ladder across dimensional boundaries. Each ascension reveals that previous reality was just another floor. The 13th step promises exit, but cycles restart endlessly. Perhaps escape is the real prison.",
    image: "/thumbnails/13-steps-to-escape.png",
    seoKeywords: ['dimensional escape ladder game', 'iterative reality climbing', 'thirteen-step portal puzzle', 'cyclical dimension maze', 'impossible exit simulator'],
    occultTheme: 'breach-anomalies',
    thumbnail: '🌌',
    category: 'web_games',
    icon: '🌌',
    path: '/game/13-steps-to-escape',
    tags: ['auto-classified', 'web_games', 'puzzle', 'exploration'],
    play_count: 0,
  },
  {
    id: 'witchcat',
    title: 'witchcat',
    description: '🎮 Mystical feline sorcery with supernatural gameplay mechanics.',
    controls: "⌨️ [Arrow Keys/WASD] Move | [Space] Cast Spell | 🖱️ [Click] Target Enemies",
    storyDescription: "An ancient witch bound her soul to a black cat, granting it arcane powers. Navigate cursed forests where spectral guardians test your mastery of forbidden spells. Every shadow whispers secrets of necromancers long forgotten.",
    image: "/thumbnails/witchcat.png",
    seoKeywords: ['witch cat game', 'mystical magic simulator', 'spectral guardian battle', 'supernatural spell casting', 'forbidden grimoire adventure'],
    occultTheme: 'necromancy-spirits',
    thumbnail: '💀',
    category: 'web_games',
    icon: '💀',
    path: '/game/witchcat',
    tags: ['auto-classified', 'web_games', 'magic', 'occult'],
    play_count: 0,
  },
  {
    id: 'whiskers-witch-adventure',
    title: 'whiskers-witch-adventure',
    description: '🎮 Magical cat adventure featuring mystical transmutation and potion brewing.',
    controls: "⌨️ [Arrow Keys/WASD] Move | [E] Interact | 🖱️ [Click] Brew Potion",
    storyDescription: "Whiskers the witch cat discovers ancient alchemical formulas hidden in enchanted libraries. Gather forbidden ingredients, transmute matter into power, and uncover a conspiracy of dark mages. The boundary between alchemy and sorcery blurs with each ritual.",
    image: "/thumbnails/whiskers-witch-adventure.png",
    seoKeywords: ['alchemy adventure game', 'potion brewing simulator', 'transmutation magic', 'witchcraft exploration', 'magical ingredient collection'],
    occultTheme: 'alchemy-dark-magic',
    thumbnail: '⚗️',
    category: 'web_games',
    icon: '⚗️',
    path: '/game/whiskers-witch-adventure',
    tags: ['auto-classified', 'web_games', 'alchemy', 'adventure'],
    play_count: 0,
  },
  {
    id: 'triska-the-ninja-cat',
    title: 'triska-the-ninja-cat',
    description: '🎮 Fluid ninja combat action featuring gravity-defying parkour moves.',
    controls: "⌨️ [WASD] Move | [Space] Jump | 🖱️ [Click] Strike | [Shift] Dash",
    storyDescription: "Triska the shadow cat defies the laws of physics with impossible movements. Her strikes bend reality itself, leaving temporal rifts in her wake. Navigate anomalous dojo chambers where gravity flows sideways and walls exist in multiple dimensions simultaneously.",
    image: "/thumbnails/triska-the-ninja-cat.png",
    seoKeywords: ['gravity defying ninja game', 'anomalous parkour combat', 'shadow cat assassin', 'dimensional dojo simulator', 'physics-bending action'],
    occultTheme: 'anomalous-physics',
    thumbnail: '⚡',
    category: 'web_games',
    icon: '⚡',
    path: '/game/triska-the-ninja-cat',
    tags: ['auto-classified', 'web_games', 'action', 'ninja'],
    play_count: 0,
  },
  {
    id: 'non-mewtonian-cat',
    title: 'non-mewtonian-cat',
    description: '🎮 Solve puzzles with impossible physics and non-Newtonian fluids.',
    controls: "⌨️ [WASD] Navigate | 🖱️ [Click] Manipulate Fluid | [R] Reset Level",
    storyDescription: "In the Non-Mewtonian Laboratory, fluid behaves against all known laws of physics. A curious cat experiments with matter that solidifies under pressure and flows like water otherwise. Each puzzle defies conventional understanding of cause and effect.",
    image: "/thumbnails/non-mewtonian-cat.png",
    seoKeywords: ['non-Newtonian physics game', 'anomalous fluid puzzle', 'impossible matter simulator', 'physics paradox adventure', 'laboratory cat explorer'],
    occultTheme: 'anomalous-physics',
    thumbnail: '⚡',
    category: 'web_games',
    icon: '⚡',
    path: '/game/non-mewtonian-cat',
    tags: ['auto-classified', 'web_games', 'puzzle', 'physics'],
    play_count: 0,
  },
  {
    id: 'kuro-neko-market',
    title: 'kuro-neko-market',
    description: '🎮 Navigate a mystical marketplace where sacred geometry unlocks hidden treasures.',
    controls: "🖱️ [Mouse] Navigate Stalls | [Click] Trade | [Space] Reveal Pattern",
    storyDescription: "The Black Cat Market exists in geometric space where dimensions fold into perfect angles. Sacred symbols guide traders through crystalline halls where each transaction aligns cosmic forces. Numbers whisper ancient truths about the universe's underlying mathematics.",
    image: "/thumbnails/kuro-neko-market.png",
    seoKeywords: ['sacred geometry marketplace', 'dimensional trading game', 'mystical pattern recognition', 'cosmic alignment simulator', 'geometric puzzle commerce'],
    occultTheme: 'sacred-geometry',
    thumbnail: '✨',
    category: 'web_games',
    icon: '✨',
    path: '/game/kuro-neko-market',
    tags: ['auto-classified', 'web_games', 'trading', 'geometry'],
    play_count: 0,
  },
  {
    id: 'kittens-united',
    title: 'kittens-united',
    description: '🎮 Cooperative puzzle adventure where cats harness geometric harmony.',
    controls: "⌨️ [WASD] Move | [E] Cooperate | 🖱️ [Click] Activate Symbol",
    storyDescription: "United kittens discover that harmony requires perfect geometric arrangement. Each formation creates resonance between dimensions, unlocking pathways through crystalline caverns. Together, they learn the sacred language of spatial perfection.",
    image: "/thumbnails/kittens-united.png",
    seoKeywords: ['cooperative puzzle game', 'geometric harmony simulator', 'sacred kitten adventure', 'dimensional puzzle solving', 'crystal maze exploration'],
    occultTheme: 'sacred-geometry',
    thumbnail: '✨',
    category: 'web_games',
    icon: '✨',
    path: '/game/kittens-united',
    tags: ['auto-classified', 'web_games', 'cooperative', 'puzzle'],
    play_count: 0,
  },
  {
    id: 'echoes-of-nyx',
    title: 'echoes-of-nyx',
    description: '🎮 Experience cosmic horror through the eyes of entities beyond comprehension.',
    controls: "⌨️ [Arrow Keys] Explore | 🖱️ [Click] Investigate | [Space] Document",
    storyDescription: "Nyx whispers across the void, her echoes reaching into realities where sanity dissolves. Ancient entities stir in the cosmic abyss, aware of your presence yet incomprehensibly distant. What you observe transforms as the observer becomes the observed.",
    image: "/thumbnails/echoes-of-nyx.png",
    seoKeywords: ['cosmic horror experience', 'void entity encounter', 'sanity-breaking simulator', 'interdimensional mystery game', 'eldritch investigation'],
    occultTheme: 'cosmic-horror',
    thumbnail: '👁️',
    category: 'web_games',
    icon: '👁️',
    path: '/game/echoes-of-nyx',
    tags: ['auto-classified', 'web_games', 'horror', 'cosmic'],
    play_count: 0,
  },
  {
    id: 'celestial-paws',
    title: 'celestial-paws',
    description: '🎮 A cosmic journey through sacred patterns and stellar alignments.',
    controls: "🖱️ [Mouse] Draw Constellation | [Space] Align Stars | [R] Reset Pattern",
    storyDescription: "Celestial Paws walks across star paths where each paw print creates geometric harmony. Constellations form from sacred angles, unlocking doorways between cosmic realms. The cat discovers that all creation follows mathematical perfection.",
    image: "/thumbnails/celestial-paws.png",
    seoKeywords: ['constellation puzzle game', 'celestial geometry simulator', 'star alignment adventure', 'cosmic pattern creator', 'sacred astral journey'],
    occultTheme: 'sacred-geometry',
    thumbnail: '✨',
    category: 'web_games',
    icon: '✨',
    path: '/game/celestial-paws',
    tags: ['auto-classified', 'web_games', 'cosmic', 'geometry'],
    play_count: 0,
  },
  {
    id: 'catculus',
    title: 'catculus',
    description: '🎮 Master the mathematics of impossible physics and dimensional calculations.',
    controls: "⌨️ [Arrow Keys] Navigate Equation | 🖱️ [Click] Solve | [Space] Calculate",
    storyDescription: "Catculus explores a mathematical realm where physics equations rewrite themselves. The cat manipulates gravity, trajectory, and dimensional constants. Each formula solved bends reality further, revealing that mathematics itself is alive and anomalous.",
    image: "/thumbnails/catculus.png",
    seoKeywords: ['mathematical physics game', 'anomalous calculation simulator', 'gravity equation puzzle', 'dimensional math adventure', 'reality bending formula'],
    occultTheme: 'anomalous-physics',
    thumbnail: '⚡',
    category: 'web_games',
    icon: '⚡',
    path: '/game/catculus',
    tags: ['auto-classified', 'web_games', 'math', 'physics'],
    play_count: 0,
  },
  {
    id: 'black-cat-squadron',
    title: 'black-cat-squadron',
    description: '🎮 Command a squadron of felines through gravity-defying aerial combat.',
    controls: "⌨️ [WASD] Move Squadron | [Space] Attack Formation | 🖱️ [Click] Precision Strike",
    storyDescription: "The Black Cat Squadron operates in a realm where gravity becomes tactical. Pilots navigate aerial anomalies, defying conventional flight physics. Each maneuver exploits dimensional instabilities, turning impossible trajectories into devastating strategies.",
    image: "/thumbnails/black-cat-squadron.png",
    seoKeywords: ['gravity combat game', 'anomalous flight simulator', 'dimensional warfare', 'tactical physics combat', 'squad anomaly flight'],
    occultTheme: 'anomalous-physics',
    thumbnail: '⚡',
    category: 'web_games',
    icon: '⚡',
    path: '/game/black-cat-squadron',
    tags: ['auto-classified', 'web_games', 'action', 'squadron'],
    play_count: 0,
  },
  {
    id: 'ashes-of-ulthar',
    title: 'ashes-of-ulthar',
    description: '🎮 Explore the ruins of an impossible city lost to cosmic forces.',
    controls: "⌨️ [Arrow Keys] Explore Ruins | 🖱️ [Click] Examine Artifacts | [Space] Meditate",
    storyDescription: "Ulthar fell to cosmic horrors beyond mortal understanding. Its ashes hold echoes of entities that devour dimensions. To survive its ruins is to touch the incomprehensible. Each discovery reveals that Ulthar was never meant for human eyes.",
    image: "/thumbnails/ashes-of-ulthar.png",
    seoKeywords: ['cosmic ruin exploration', 'eldritch city simulator', 'impossible architecture game', 'sanity-breaking discovery', 'void artifact investigation'],
    occultTheme: 'cosmic-horror',
    thumbnail: '👁️',
    category: 'web_games',
    icon: '👁️',
    path: '/game/ashes-of-ulthar',
    tags: ['auto-classified', 'web_games', 'exploration', 'cosmic'],
    play_count: 0,
  },
  {
    id: 'unifrost',
    title: 'unifrost',
    description: '🌌 Navigate an interdimensional crystalline landscape of impossible geometry.',
    controls: "⌨️ [Arrow Keys] Navigate | 🖱️ [Click] Scan | [Space] Warp",
    storyDescription: "Unifrost exists between dimensions as a realm of eternal winter and cosmic dread. Ancient intelligences observe from the frozen void. The landscape reshapes based on observation—a universe that fears being perceived, yet demands attention.",
    image: "/thumbnails/unifrost.png",
    seoKeywords: ['interdimensional exploration', 'cosmic horror landscape', 'frozen void simulator', 'dimensional observation game', 'eldritch terrain navigator'],
    occultTheme: 'cosmic-horror',
    thumbnail: '👁️',
    category: 'simulation',
    icon: '👁️',
    path: '/game/unifrost',
    tags: ['auto-classified', 'space_universe', 'cosmic', 'exploration'],
    play_count: 0,
  },
  {
    id: 'unicorn-fireball',
    title: 'unicorn-fireball',
    description: '🎮 Defy gravity with explosive magical projectiles and impossible trajectories.',
    controls: "⌨️ [WASD] Move | [Space] Jump | 🖱️ [Click] Fire | [Shift] Boost",
    storyDescription: "A magical unicorn harnesses fireballs that follow anomalous physics laws. Gravity inverts mid-flight, trajectories loop through dimensions. The more power unleashed, the more reality distorts around impact zones.",
    image: "/thumbnails/unicorn-fireball.png",
    seoKeywords: ['gravity defying projectile game', 'magical physics simulator', 'anomalous trajectory combat', 'explosive physics puzzle', 'dimensional fireball adventure'],
    occultTheme: 'anomalous-physics',
    thumbnail: '⚡',
    category: 'web_games',
    icon: '⚡',
    path: '/game/unicorn-fireball',
    tags: ['auto-classified', 'web_games', 'action', 'magic'],
    play_count: 0,
  },
  {
    id: 'swinicorn',
    title: 'swinicorn',
    description: '🎮 A magical swine navigates sacred geometry patterns to achieve cosmic balance.',
    controls: "⌨️ [Arrow Keys] Move | 🖱️ [Click] Align | [Space] Balance",
    storyDescription: "The Swinicorn moves through perfectly tessellated dimensions where each step creates geometric harmony. Sacred patterns flow through its hooves, and the universe responds with light. Balance achieved through perfect mathematical form.",
    image: "/thumbnails/swinicorn.png",
    seoKeywords: ['sacred geometry swine', 'cosmic balance simulator', 'pattern alignment game', 'tessellation puzzle', 'magical symmetry adventure'],
    occultTheme: 'sacred-geometry',
    thumbnail: '✨',
    category: 'web_games',
    icon: '✨',
    path: '/game/swinicorn',
    tags: ['auto-classified', 'web_games', 'magic', 'geometry'],
    play_count: 0,
  },
  {
    id: 'suupaa-yunikoon',
    title: 'suupaa-yunikoon',
    description: '🌌 A super unicorn challenges cosmic entities across dimensional boundaries.',
    controls: "⌨️ [Arrow Keys] Navigate | [Space] Power Attack | 🖱️ [Click] Blast",
    storyDescription: "Suupaa Yunikoon emerges as cosmic forces align, possessing power to challenge void entities. Its horn pierces dimensional barriers, each strike resonating across impossible geometries. The cosmos itself trembles at this being's existence.",
    image: "/thumbnails/suupaa-yunikoon.png",
    seoKeywords: ['cosmic entity battle', 'dimensional unicorn game', 'void warrior simulator', 'interdimensional combat', 'eldritch power fantasy'],
    occultTheme: 'cosmic-horror',
    thumbnail: '👁️',
    category: 'simulation',
    icon: '👁️',
    path: '/game/suupaa-yunikoon',
    tags: ['auto-classified', 'space_universe', 'cosmic', 'action'],
    play_count: 0,
  },
  {
    id: 'spectral-horn',
    title: 'spectral-horn',
    description: '🎮 Channel spectral energy through geometric harmonics and sacred forms.',
    controls: "🖱️ [Mouse] Draw Pattern | [Space] Resonate | [E] Transmit Energy",
    storyDescription: "The Spectral Horn resonates with geometric frequencies where matter and spirit intertwine. Sacred angles amplify supernatural power, creating spirals of energy. Those who hear its call experience perfect mathematical enlightenment.",
    image: "/thumbnails/spectral-horn.png",
    seoKeywords: ['spectral energy geometry', 'sacred resonance simulator', 'geometric power channeling', 'harmonic alignment game', 'mystical frequency adventure'],
    occultTheme: 'sacred-geometry',
    thumbnail: '✨',
    category: 'web_games',
    icon: '✨',
    path: '/game/spectral-horn',
    tags: ['auto-classified', 'web_games', 'mystical', 'geometry'],
    play_count: 0,
  },
  {
    id: 'sp13ktra-main',
    title: 'sp13ktra-main',
    description: '🎮 Decipher spectral anomalies through defiant physics manipulation.',
    controls: "⌨️ [Arrow Keys] Scan | 🖱️ [Click] Interact | [Space] Pulse Detector",
    storyDescription: "Sp13ktra intercepted anomalous signals violating fundamental physics laws. Investigating the source reveals equipment that shouldn't exist, mathematics that rewrites reality itself. The deeper the scan, the more reality fractures.",
    image: "/thumbnails/sp13ktra-main.png",
    seoKeywords: ['anomalous signal detector', 'physics violation game', 'spectral anomaly investigation', 'impossible physics simulator', 'reality fracture puzzle'],
    occultTheme: 'anomalous-physics',
    thumbnail: '⚡',
    category: 'web_games',
    icon: '⚡',
    path: '/game/sp13ktra-main',
    tags: ['auto-classified', 'web_games', 'science', 'anomaly'],
    play_count: 0,
  },
  {
    id: 'seven-cushions',
    title: 'seven-cushions',
    description: '🎮 Decode abyssal frequencies transmitted through dimensional rifts.',
    controls: "🖱️ [Mouse] Tune Frequency | [Space] Record Signal | [E] Decode",
    storyDescription: "Seven cushions positioned to receive transmissions from the abyss. Each signal grows louder, clearer, more insistent. The patterns suggest intelligence—something calling from the depths of reality itself. The frequencies are becoming urgent.",
    image: "/thumbnails/seven-cushions.png",
    seoKeywords: ['abyssal frequency decoder', 'dimensional signal game', 'void communication simulator', 'frequency anomaly puzzle', 'abyss transmission adventure'],
    occultTheme: 'abyssal-frequencies',
    thumbnail: '🔮',
    category: 'web_games',
    icon: '🔮',
    path: '/game/seven-cushions',
    tags: ['auto-classified', 'web_games', 'audio', 'mystery'],
    play_count: 0,
  },
  {
    id: 'rainbow-rescue',
    title: 'rainbow-rescue',
    description: '🎮 Navigate optical illusions and perceptual anomalies to save trapped souls.',
    controls: "⌨️ [WASD] Move | 🖱️ [Click] Interact | [Space] Break Illusion",
    storyDescription: "Rainbow streams hide darker truths—carefully constructed illusions designed to ensnare consciousness. Rescue missions require distinguishing real from fabricated reality. Each save pulls another soul from the hallucinogenic labyrinth.",
    image: "/thumbnails/rainbow-rescue.png",
    seoKeywords: ['illusion puzzle game', 'perceptual anomaly rescue', 'reality distortion simulator', 'hallucination maze puzzle', 'consciousness trap escape'],
    occultTheme: 'illusions-hallucinations',
    thumbnail: '🎭',
    category: 'web_games',
    icon: '🎭',
    path: '/game/rainbow-rescue',
    tags: ['auto-classified', 'web_games', 'puzzle', 'rescue'],
    play_count: 0,
  },
  {
    id: 'prismhoof',
    title: 'prismhoof',
    description: '🎮 A hoofed being steps through sacred geometry crystalline formations.',
    controls: "⌨️ [Arrow Keys] Step | 🖱️ [Click] Refract Light | [Space] Transmute",
    storyDescription: "Prismhoof walks paths where light becomes solid and geometry breathes. Each hoof step creates perfect angles that reshape the environment. The universe responds to this being's sacred geometry, shifting to accommodate its spiritual mathematics.",
    image: "/thumbnails/prismhoof.png",
    seoKeywords: ['prism geometry game', 'light refraction simulator', 'sacred step puzzle', 'crystalline geometry adventure', 'harmonic pattern guide'],
    occultTheme: 'sacred-geometry',
    thumbnail: '✨',
    category: 'web_games',
    icon: '✨',
    path: '/game/prismhoof',
    tags: ['auto-classified', 'web_games', 'magic', 'geometry'],
    play_count: 0,
  },
  {
    id: 'gjallarhorn',
    title: 'gjallarhorn',
    description: '🎮 Summon power from abyssal depths to sound reality-shattering frequencies.',
    controls: "🖱️ [Mouse] Aim | [Space] Charge | [Click] Release Blast",
    storyDescription: "Gjallarhorn amplifies signals from the abyss until reality trembles. Each activation sends frequency pulses that reshape dimensional boundaries. The horn remembers elder times when it summoned apocalyptic convergences.",
    image: "/thumbnails/gjallarhorn.png",
    seoKeywords: ['abyssal resonance game', 'frequency amplitude simulator', 'reality shatter puzzle', 'dimensional frequency blast', 'abyss summon adventure'],
    occultTheme: 'abyssal-frequencies',
    thumbnail: '🔮',
    category: 'web_games',
    icon: '🔮',
    path: '/game/gjallarhorn',
    tags: ['auto-classified', 'web_games', 'power', 'mystery'],
    play_count: 0,
  },
  {
    id: 'at-both-ends',
    title: 'at-both-ends',
    description: '🎮 Navigate a reality fractured by simultaneous dimensional ruptures.',
    controls: "⌨️ [WASD] Navigate Breach | 🖱️ [Click] Seal Rift | [Space] Phase Shift",
    storyDescription: "Reality tears simultaneously at both ends—breaches spreading through interconnected dimensions. Walking the middle ground between expanding rifts tests sanity itself. Each sealed rupture opens others elsewhere. The breaches are self-perpetuating.",
    image: "/thumbnails/at-both-ends.png",
    seoKeywords: ['dimensional breach game', 'reality rupture simulator', 'breach navigation puzzle', 'rift sealing adventure', 'parallel fracture escape'],
    occultTheme: 'breach-anomalies',
    thumbnail: '🌌',
    category: 'web_games',
    icon: '🌌',
    path: '/game/at-both-ends',
    tags: ['auto-classified', 'web_games', 'puzzle', 'dimensional'],
    play_count: 0,
  },
  {
    id: 'xx142-b2exe',
    title: 'xx142-b2exe',
    description: '🌌 Execute classified protocols in an interdimensional research installation.',
    controls: "⌨️ [Arrow Keys] Navigate Terminal | 🖱️ [Click] Execute Command | [Space] Override",
    storyDescription: "Designation XX-142-B2 runs protocols in reality-adjacent space. The executable contains cosmic anomalies awaiting activation. With each command executed, the barriers between dimensions weaken further. Termination protocols activate if sequence completes.",
    image: "/thumbnails/xx142-b2exe.png",
    seoKeywords: ['cosmic anomaly executor', 'classified protocol game', 'dimensional research simulator', 'eldritch command line', 'reality interface puzzle'],
    occultTheme: 'cosmic-horror',
    thumbnail: '👁️',
    category: 'simulation',
    icon: '👁️',
    path: '/game/xx142-b2exe',
    tags: ['auto-classified', 'space_universe', 'cosmic', 'classified'],
    play_count: 0,
  },
  {
    id: 'underrun',
    title: 'underrun',
    description: '🎮 Escape expanding dimensional rifts beneath collapsing reality layers.',
    controls: "⌨️ [WASD] Sprint | [Space] Jump | 🖱️ [Click] Slash Rift | [Shift] Boost",
    storyDescription: "Underrun through collapsing reality corridors where breaches multiply behind you. The ground itself tears open, rifts swallowing the past. Speed is survival. The deeper you go, the more dimensional anomalies converge.",
    image: "/thumbnails/underrun.png",
    seoKeywords: ['dimensional escape runner', 'reality collapse game', 'rift pursuit simulator', 'breach evasion adventure', 'collapsing dimension obstacle'],
    occultTheme: 'breach-anomalies',
    thumbnail: '🌌',
    category: 'web_games',
    icon: '🌌',
    path: '/game/underrun',
    tags: ['auto-classified', 'web_games', 'action', 'runner'],
    play_count: 0,
  },
  {
    id: 'systems-offline',
    title: 'systems-offline',
    description: '🌌 Systems fail as cosmic entities exert control over dimensional infrastructure.',
    controls: "🖱️ [Mouse] Restore Systems | [Space] Reroute Power | [E] Manual Override",
    storyDescription: "All systems collapse simultaneously across interdimensional networks. Cosmic intelligences disable infrastructure methodically. With each restoration attempt, systems fail differently. The entities are learning. The installation falls deeper under their control.",
    image: "/thumbnails/systems-offline.png",
    seoKeywords: ['system failure simulator', 'cosmic shutdown game', 'dimensional infrastructure puzzle', 'entity control invasion', 'infrastructure collapse adventure'],
    occultTheme: 'cosmic-horror',
    thumbnail: '👁️',
    category: 'simulation',
    icon: '👁️',
    path: '/game/systems-offline',
    tags: ['auto-classified', 'space_universe', 'cosmic', 'system'],
    play_count: 0,
  },
  {
    id: 'panzercorn',
    title: 'panzercorn',
    description: '🎮 Command an armor-plated unicorn protecting forbidden biological specimens.',
    controls: "⌨️ [WASD] Move Tank | [Space] Charge | 🖱️ [Click] Cannon Fire",
    storyDescription: "Panzercorn guards specimens that shouldn't exist—genetic abominations combining life forms in violation of natural law. Each specimen exhibits adaptive mutations. The armor protects the warden from contamination. The specimens are evolving.",
    image: "/thumbnails/panzercorn.png",
    seoKeywords: ['biological specimen guardian', 'forbidden creature game', 'genetic anomaly simulator', 'mutation defense puzzle', 'biological horror adventure'],
    occultTheme: 'forbidden-specimens',
    thumbnail: '🧬',
    category: 'web_games',
    icon: '🧬',
    path: '/game/panzercorn',
    tags: ['auto-classified', 'web_games', 'action', 'defense'],
    play_count: 0,
  },
  {
    id: 'merlin-vs-alfonso',
    title: 'merlin-vs-alfonso',
    description: '🎮 Ancient wizards duel using transmutation and forbidden alchemical arts.',
    controls: "⌨️ [WASD] Position | [Space] Cast Spell | 🖱️ [Click] Transmute",
    storyDescription: "Merlin and Alfonso clash in a duel spanning centuries and dimensions. Their alchemy rewrites matter itself. Each spell layers transformations—lead becomes gold becomes something beyond atomic structure. The duel continues across multiple realities.",
    image: "/thumbnails/merlin-vs-alfonso.png",
    seoKeywords: ['alchemical duel game', 'wizard transmutation battle', 'forbidden spell casting', 'matter transformation combat', 'century spanning magic'],
    occultTheme: 'alchemy-dark-magic',
    thumbnail: '⚗️',
    category: 'web_games',
    icon: '⚗️',
    path: '/game/merlin-vs-alfonso',
    tags: ['auto-classified', 'web_games', 'magic', 'duel'],
    play_count: 0,
  },
  {
    id: 'huecorn',
    title: 'huecorn',
    description: '🎮 A colorful unicorn dances through sacred geometric light patterns.',
    controls: "🖱️ [Mouse] Draw Rainbow | [Space] Activate Pattern | [E] Harmonize",
    storyDescription: "Huecorn exists as pure geometric light, each movement creating sacred color patterns. The spectrum it creates resonates with dimensional harmonics. Perfect hue combinations unlock pathways between worlds. Beauty and mathematics become one.",
    image: "/thumbnails/huecorn.png",
    seoKeywords: ['color geometry game', 'sacred light pattern', 'harmonic rainbow simulator', 'dimensional color puzzle', 'geometric light adventure'],
    occultTheme: 'sacred-geometry',
    thumbnail: '✨',
    category: 'web_games',
    icon: '✨',
    path: '/game/huecorn',
    tags: ['auto-classified', 'web_games', 'artistic', 'geometry'],
    play_count: 0,
  },
  {
    id: 'edge-not-found',
    title: 'edge-not-found',
    description: '🎮 Search for boundaries in a reality where edges keep dissolving.',
    controls: "⌨️ [Arrow Keys] Navigate Void | 🖱️ [Click] Mark Edge | [Space] Scan",
    storyDescription: "The Edge of Reality vanished. Dimensional boundaries dissolve when observed. Navigation becomes impossible when coordinates don't exist. Searching for endpoints in infinite space. The rifts spread. The edges keep fragmenting.",
    image: "/thumbnails/edge-not-found.png",
    seoKeywords: ['dimensional boundary explorer', 'void navigation game', 'reality edge simulator', 'boundary dissolution puzzle', 'infinite space anomaly'],
    occultTheme: 'breach-anomalies',
    thumbnail: '🌌',
    category: 'web_games',
    icon: '🌌',
    path: '/game/edge-not-found',
    tags: ['auto-classified', 'web_games', 'exploration', 'anomaly'],
    play_count: 0,
  },
  {
    id: 'dying-dreams',
    title: 'dying-dreams',
    description: '🎮 Navigate the final moments of consciousness as reality fades.',
    controls: "⌨️ [WASD] Walk Memory | 🖱️ [Click] Examine Echo | [Space] Fade",
    storyDescription: "As consciousness dies, memories fragment across dimensions. Echoes of lived moments haunt the void. Walking through dying dreams reveals that death was never the end—merely a transition to watching other realities collapse. Spirits witness infinity ending.",
    image: "/thumbnails/dying-dreams.png",
    seoKeywords: ['death consciousness game', 'memory fragment explorer', 'spirit realm simulator', 'afterlife mystery puzzle', 'fading reality adventure'],
    occultTheme: 'necromancy-spirits',
    thumbnail: '💀',
    category: 'web_games',
    icon: '💀',
    path: '/game/dying-dreams',
    tags: ['auto-classified', 'web_games', 'mystery', 'surreal'],
    play_count: 0,
  },
  {
    id: 'coup-ahoo',
    title: 'coup-ahoo',
    description: '🎮 Uncover conspiracies hidden beneath layers of collaborative illusion.',
    controls: "⌨️ [WASD] Investigate | 🖱️ [Click] Reveal Truth | [Space] Break Spell",
    storyDescription: "Coup-Ahoo investigates a conspiracy woven from shared illusions. Each conspirator maintains the fabrication through synchronized hallucination. Revealing one layer exposes deeper deceptions. The conspiracy may be the only reality holding fragments together.",
    image: "/thumbnails/coup-ahoo.png",
    seoKeywords: ['conspiracy illusion game', 'hallucination reality puzzle', 'perception manipulation game', 'truth revelation simulator', 'illusion layer mystery'],
    occultTheme: 'illusions-hallucinations',
    thumbnail: '🎭',
    category: 'web_games',
    icon: '🎭',
    path: '/game/coup-ahoo',
    tags: ['auto-classified', 'web_games', 'mystery', 'puzzle'],
    play_count: 0,
  },
  {
    id: 'cat-survivors',
    title: 'cat-survivors',
    description: '🎮 A feline pack endures an apocalypse of spectral forces.',
    controls: "⌨️ [Arrow Keys] Move Pack | [Space] Defend | 🖱️ [Click] Attack Spirit",
    storyDescription: "The Cat Survivors emerged from mass death events, now hunted by the very spirits they once were. Spectral forces grow stronger each night. The pack understands that true survival means transcending the boundary between life and death entirely.",
    image: "/thumbnails/cat-survivors.png",
    seoKeywords: ['spirit survival game', 'necromantic apocalypse', 'spectral creature combat', 'undead evasion simulator', 'survival paranormal adventure'],
    occultTheme: 'necromancy-spirits',
    thumbnail: '💀',
    category: 'web_games',
    icon: '💀',
    path: '/game/cat-survivors',
    tags: ['auto-classified', 'web_games', 'survival', 'action'],
    play_count: 0,
  },
  {
    id: 'bounce-back',
    title: 'bounce-back',
    description: '🎮 Exploit gravity anomalies to ricochet through impossible architecture.',
    controls: "⌨️ [WASD] Position | [Space] Bounce | 🖱️ [Click] Redirect Gravity",
    storyDescription: "Gravity inverts unpredictably, making bouncing the only navigation method. Each ricocket travels at impossible angles. Mastering anomalous physics means survival. Walls become floors. Momentum reverses. Gravity flows sideways.",
    image: "/thumbnails/bounce-back.png",
    seoKeywords: ['gravity anomaly platformer', 'bounce physics puzzle', 'impossible architecture game', 'gravity manipulation simulator', 'physics defiance adventure'],
    occultTheme: 'anomalous-physics',
    thumbnail: '⚡',
    category: 'web_games',
    icon: '⚡',
    path: '/game/bounce-back',
    tags: ['auto-classified', 'web_games', 'platformer', 'physics'],
    play_count: 0,
  },
  {
    id: 'beat-rocks',
    title: 'beat-rocks',
    description: '🎮 Break anomalous stone formations that defy impact physics.',
    controls: "⌨️ [Arrow Keys] Aim | [Space] Strike | 🖱️ [Click] Power Hit",
    storyDescription: "Anomalous rocks shatter in unexpected ways—impacts reverberate through dimensions. Breaking one creates shockwaves affecting others across spatial boundaries. Each rock destroyed redistributes physics laws. The entire landscape is interconnected.",
    image: "/thumbnails/beat-rocks.png",
    seoKeywords: ['anomalous rock breaker', 'physics impact simulator', 'shockwave puzzle game', 'dimensional rock destruction', 'impact anomaly adventure'],
    occultTheme: 'anomalous-physics',
    thumbnail: '⚡',
    category: 'web_games',
    icon: '⚡',
    path: '/game/beat-rocks',
    tags: ['auto-classified', 'web_games', 'action', 'puzzle'],
    play_count: 0,
  },
  {
    id: '13th-floor',
    title: '13th-floor',
    description: '🎮 Investigate a facility where reality bends and time loops collapse.',
    controls: '⌨️ [W][A][S][D] or [Arrow Keys] to Navigate | 🖱️ [Click] to Interact with Objects | [E] to Examine',
    storyDescription: 'An anomalous energy signature detected on floor 13 of the classified research facility. Traverse through mysterious corridors where reality bends and time loops collapse. Uncover the truth hidden between dimensions.',
    image: '/thumbnails/13th-floor.png',
    seoKeywords: ['13th floor mystery', 'dimensional anomaly game', 'classified facility simulator', 'reality bending puzzle', 'temporal loop investigation'],
    occultTheme: 'abyssal-frequencies',
    thumbnail: '🔮',
    category: 'web_games',
    icon: '🔮',
    path: '/game/13th-floor',
    tags: ['auto-classified', 'web_games', 'mystery', 'dimensional'],
    play_count: 0,
  },
  {
    id: 'ninja-vs-evilcorp',
    title: 'ninja-vs-evilcorp',
    description: '🎮 Infiltrate corporate darkness wielding ancient technique and experimental weaponry.',
    controls: '⌨️ [W][A][S][D] to Move | [Space] to Jump/Dodge | 🖱️ [Left Click] Attack | [Shift] Stealth Mode',
    storyDescription: 'A classified operative infiltrates the darkest corners of EvilCorp headquarters. Armed with ancient ninja techniques and experimental weapons, navigate through shadowy corridors. Every shadow conceals a secret. Every corner holds a trap.',
    image: '/thumbnails/ninja-vs-evilcorp.png',
    seoKeywords: ['ninja stealth game', 'espionage action game', 'classified operative mission', 'dark corporate infiltration', 'shadow operative adventure'],
    occultTheme: 'abyssal-frequencies',
    thumbnail: '🔮',
    category: 'web_games',
    icon: '🔮',
    path: '/game/ninja-vs-evilcorp',
    tags: ['auto-classified', 'web_games', 'action', 'stealth'],
    play_count: 0,
  },
  {
    id: 'dante',
    title: 'Dante - Dimensional Puzzle',
    description: '🔮 Navigate surreal dimensional puzzles through fractured realities.',
    controls: '🖱️ [Click/Drag] Objects to Solve Puzzles | [WASD/Arrows] to Move | [Mouse] to Explore | [R] to Reset Room',
    storyDescription: 'Dante awakens in a labyrinth of fractured realities. Each room defies the laws of physics, each puzzle whispers of a forgotten civilization. Solve dimensional anomalies to escape the ever-shifting depths of parallel existence.',
    image: '/thumbnails/dante.png',
    seoKeywords: ['dimensional puzzle game', 'surreal reality simulator', 'quantum maze adventure', 'metaphysical puzzle solver', 'parallel world escape'],
    occultTheme: 'abyssal-frequencies',
    thumbnail: '🔮',
    category: 'simulation',
    icon: '🔮',
    path: '/game/dante',
    tags: ['experimental', 'classified', 'mystery', 'puzzle', 'adventure', 'dimensional'],
    play_count: 0,
  },
  {
    id: 'clawstrike',
    title: 'Clawstrike - Battle Arena',
    description: '⚔️ Combat against mysterious entities wielding exotic energy attacks.',
    controls: '🖱️ [Click] to Attack | [WASD/Arrows] to Dodge | [Space] Defend | Hold [Q] for Power Attack',
    storyDescription: 'Face unknown entities in an interdimensional battle arena. Their claws crackle with exotic energy. Your reflexes are your only defense. Survive the gauntlet and discover the source of their power.',
    image: '/thumbnails/clawstrike.png',
    seoKeywords: ['interdimensional combat', 'exotic entity battle game', 'arena action simulator', 'alien creature fighter', 'dimensional combat arena'],
    occultTheme: 'abyssal-frequencies',
    thumbnail: '🔮',
    category: 'simulation',
    icon: '🔮',
    path: '/game/clawstrike',
    tags: ['experimental', 'classified', 'mystery', 'action', 'combat', 'entity'],
    play_count: 0,
  },
  {
    id: 'neon-platformer',
    title: 'Neon Platformer - Premium Edition',
    description: '🎮 Jump through neon-lit maze levels with addictive 2D platformer gameplay.',
    controls: '⌨️ [Arrow Keys] or [A][D] to Move | [Space] or [W] to Jump | [Double Jump] for Extra Height',
    storyDescription: 'Venture into a cyberpunk maze where neon highways twist through digital canyons. Electrified platforms await. Collect the scattered data nodes before the system collapse spreads further. Your journey through the neon void begins now.',
    image: '/thumbnails/neon-platformer.png',
    seoKeywords: ['cyberpunk platformer game', 'neon maze adventure', 'digital arcade challenge', 'glitch world platformer', 'neon void exploration'],
    occultTheme: 'abyssal-frequencies',
    thumbnail: '🔮',
    category: 'web_games',
    icon: '🔮',
    path: '/game/neon-platformer',
    tags: ['platformer', 'arcade', 'phaser', 'action', 'premium', 'neon', 'cyberpunk'],
    play_count: 0,
  },
  {
    id: 'neon-space-shooter',
    title: 'Neon Space Shooter',
    description: '💥 Battle through neon-glowing space with arcade shooter action.',
    controls: '⌨️ [Arrow Keys] or [WASD] to Navigate | [Space] to Fire | [Q] Power Shot | Collect Items for Powerups',
    storyDescription: 'Your starfighter pierces through an anomalous neon nebula. Hostile signatures surround you—manifestations of an electromagnetic storm made conscious. Evade. Fire. Survive the cosmic convergence.',
    image: '/thumbnails/neon-space-shooter.png',
    seoKeywords: ['space shooter game', 'neon space arcade', 'electromagnetic anomaly game', 'cosmic encounter shooter', 'neon void combat'],
    occultTheme: 'abyssal-frequencies',
    thumbnail: '🔮',
    category: 'web_games',
    icon: '🔮',
    path: '/game/neon-space-shooter',
    tags: ['shooter', 'arcade', 'neon', 'phaser', 'action', 'premium', 'space', 'cosmic'],
    play_count: 0,
  },
  {
    id: 'catch-game',
    title: 'Fruit Catch - Classic Arcade',
    description: '🎮 Catch falling fruits with precision timing and quick reflexes.',
    controls: '🖱️ [Mouse] Move Basket | [Click] Catch | Avoid Bombs | Collect Combos for Multiplier',
    storyDescription: 'A mysterious orchard glitches in and out of reality, raining fruits through dimensional fissures. Catch what falls before it vanishes. Time your reflexes perfectly as the harvest accelerates toward cosmic convergence.',
    image: '/thumbnails/catch-game.png',
    seoKeywords: ['fruit catch arcade', 'reflex challenge game', 'casual arcade classic', 'dimensional harvest simulator', 'arcade catching adventure'],
    occultTheme: 'abyssal-frequencies',
    thumbnail: '🔮',
    category: 'web_games',
    icon: '🔮',
    path: '/game/catch-game',
    tags: ['action', 'arcade', 'casual', 'phaser', 'reflex', 'dimensional'],
    play_count: 0,
  },
]

export const getGameById = (gameId: string): GameItem | undefined => {
  return GAMES_DATA.find((game) => game.id === gameId)
}

export const getGamesByCategory = (category: string): GameItem[] => {
  return GAMES_DATA.filter((game) => game.category === category)
}
