export interface GameItem {
  id: string
  title: string
  description: string
  thumbnail: string
  category: 'web_games' | 'simulation' | '3d_physics'
  icon: string
  path: string
  tags?: string[]
  play_count?: number
}

export const GAMES_DATA: GameItem[] = [
        {
    id: 'clawstrike',
    title: 'clawstrike',
    description: '🔮 미스터리한 Science - Web Games 실험실. clawstrike을 통해 미지의 영역을 탐험하세요.',
    thumbnail: '🔮',
    category: 'simulation',
    icon: '🔮',
    path: '/game/clawstrike',
    tags: ['experimental', 'classified', 'mystery', 'science_-_web_games'],
    play_count: 0,
  },
  {
    id: '13th_floor',
    title: '13th-floor',
    description: '🔮 미스터리한 Science - Web Games 실험실. 13th-floor을 통해 미지의 영역을 탐험하세요.',
    thumbnail: '🔮',
    category: 'simulation',
    icon: '🔮',
    path: '/game/13th_floor',
    tags: ['experimental', 'classified', 'mystery', 'science_-_web_games'],
    play_count: 0,
  },
  {
    id: 'spectral_horn',
    title: 'spectral-horn',
    description: '🔮 미스터리한 Abyssal Frequencies 실험실. spectral-horn을 통해 미지의 영역을 탐험하세요.',
    thumbnail: '🔮',
    category: 'web_games',
    icon: '🔮',
    path: '/game/spectral_horn',
    tags: ['experimental', 'classified', 'mystery', 'abyssal_frequencies'],
    play_count: 0,
  },
  {
    id: 'mario',
    title: 'Super Mario - HTML5',
    description: '🍄 Classic platformer reborn - Jump, run, collect coins, defeat enemies! The legendary Super Mario experience.',
    thumbnail: '🍄',
    category: 'web_games',
    icon: '🍄',
    path: '/game/mario',
    tags: ['platformer', 'classic', 'mario', 'arcade', 'action'],
    play_count: 0,
  },
  {
    id: 'tetris',
    title: 'Tetris Classic',
    description: '🎮 The iconic falling blocks puzzle - Rotate, stack, and clear lines! Endless challenge with increasing speed.',
    thumbnail: '🎮',
    category: 'web_games',
    icon: '🎮',
    path: '/game/tetris',
    tags: ['puzzle', 'classic', 'arcade', 'tetris', 'blocks'],
    play_count: 0,
  },
  {
    id: 'pacman',
    title: 'Pac-Man Arcade',
    description: '👻 Navigate the maze and eat all dots while avoiding ghosts! Classic arcade action with strategy.',
    thumbnail: '👻',
    category: 'web_games',
    icon: '👻',
    path: '/game/pacman',
    tags: ['arcade', 'classic', 'maze', 'pacman', 'action'],
    play_count: 0,
  },
  {
    id: 'snake',
    title: 'Snake Classic',
    description: '🐍 The timeless retro game - Eat food, grow longer, don\'t hit yourself! Simple rules, addictive gameplay.',
    thumbnail: '🐍',
    category: 'web_games',
    icon: '🐍',
    path: '/game/snake',
    tags: ['arcade', 'classic', 'retro', 'snake', 'action'],
    play_count: 0,
  },
  {
    id: '2048',
    title: '2048 - Classic Puzzle',
    description: '🧩 Legendary puzzle game - Slide tiles, merge numbers, reach 2048! Simple rules, infinite challenge.',
    thumbnail: '🧩',
    category: 'web_games',
    icon: '🧩',
    path: '/game/2048',
    tags: ['puzzle', 'numbers', 'classic', 'html5', 'casual'],
    play_count: 0,
  },
  {
    id: 'hextris',
    title: 'Hextris - Neon Arcade',
    description: '⚡ Fast-paced hex puzzle - Drop colorful hexagons, match colors, beat your score! Neon-powered arcade action.',
    thumbnail: '⚡',
    category: 'web_games',
    icon: '⚡',
    path: '/game/hextris',
    tags: ['puzzle', 'arcade', 'neon', 'html5', 'action'],
    play_count: 0,
  },
  {
    id: 'neon-dodge',
    title: 'Neon Dodge Arcade',
    description: '⚡ Premium arcade dodger - Navigate a neon minefield with precision. Obstacles spawn faster as your score increases. One hit and it\'s game over!',
    thumbnail: '⚡',
    category: 'web_games',
    icon: '⚡',
    path: '/game/neon-dodge',
    tags: ['action', 'arcade', 'neon', 'phaser', 'dodging', 'premium'],
    play_count: 0,
  },
  {
    id: 'breakout-arcade',
    title: 'Breakout Arcade',
    description: '🎮 Premium brick breaker - Control the paddle, launch the ball, destroy colorful brick towers. Progressive difficulty with particle effects!',
    thumbnail: '🎮',
    category: 'web_games',
    icon: '🎮',
    path: '/game/breakout-arcade',
    tags: ['breakout', 'arcade', 'phaser', 'casual', 'premium'],
    play_count: 0,
  },
  {
    id: 'neon-platformer',
    title: 'Neon Platformer',
    description: '🎮 Premium 2D platformer - Jump through neon levels, collect coins, avoid enemies. Procedurally generated difficulty!',
    thumbnail: '🎮',
    category: 'web_games',
    icon: '🎮',
    path: '/game/neon-platformer',
    tags: ['platformer', 'arcade', 'phaser', 'action', 'premium'],
    play_count: 0,
  },
  {
    id: 'neon-space-shooter',
    title: 'Neon Space Shooter',
    description: '💥 Premium 2D arcade shooter - Arrow keys to move, SPACE to shoot. Destroy waves of neon enemies in a glowing void!',
    thumbnail: '💥',
    category: 'web_games',
    icon: '💥',
    path: '/game/neon-space-shooter',
    tags: ['shooter', 'arcade', 'neon', 'phaser', 'action', 'premium'],
    play_count: 0,
  },
  {
    id: 'match3-puzzle',
    title: 'Match-3 Puzzle',
    description: '💎 Classical Match-3 puzzle gameplay - Click to select, swap adjacent tiles, match 3+ candies for big scores!',
    thumbnail: '💎',
    category: 'web_games',
    icon: '💎',
    path: '/game/match3-puzzle',
    tags: ['puzzle', 'match3', 'arcade', 'phaser', 'casual'],
    play_count: 0,
  },
  {
    id: 'snake-game',
    title: 'Snake Game',
    description: '클래식 뱀 게임 - 화살표 키로 방향을 조종하고 음식을 먹으세요! Arrow keys or WASD to control',
    thumbnail: '🐍',
    category: 'web_games',
    icon: '🐍',
    path: '/game/snake-game',
    tags: ['puzzle', 'arcade', 'classic', 'phaser'],
    play_count: 0,
  },
  {
    id: 'catch-game',
    title: 'Catch Game',
    description: '떨어지는 과일을 잡으세요! 마우스를 움직여 바구니를 제어하는 클래식 아케이드 게임',
    thumbnail: '🎮',
    category: 'web_games',
    icon: '🎮',
    path: '/game/catch-game',
    tags: ['action', 'arcade', 'casual', 'phaser'],
    play_count: 0,
  },
  {
    id: 'space-racer',
    title: 'Infinite Space Racer',
    description: '무한 우주선 레이싱 - 장애물을 피하고 최고 거리를 기록하세요!',
    thumbnail: '🚀',
    category: 'web_games',
    icon: '🚀',
    path: '/game/space-racer',
    tags: ['action', 'arcade', 'racing'],
    play_count: 2450,
  },
  {
    id: 'all-you-can-tycoon',
    title: 'All You Can Tycoon',
    description: '3D 경영 시뮬레이션 게임 - 음식점을 운영하고 부를 축적하세요!',
    thumbnail: '🏪',
    category: 'web_games',
    icon: '🏪',
    path: '/game/all-you-can-tycoon',
    tags: ['strategy', 'simulation', 'business'],
    play_count: 1800,
  },
  {
    id: 'prism-rush',
    title: 'Prism Rush',
    description: '3D 프리즘을 피해 나아가는 스릴 넘치는 게임',
    thumbnail: '✨',
    category: 'web_games',
    icon: '✨',
    path: '/game/prism-rush',
    tags: ['action', 'puzzle', 'arcade'],
    play_count: 3200,
  },
  {
    id: 'drift-boss',
    title: 'Drift Boss',
    description: '지그재그 길을 따라 계속 나아가는 하이퍼 캐주얼 게임 - 스페이스바를 눌러 우회전!',
    thumbnail: '🚗',
    category: 'web_games',
    icon: '🚗',
    path: '/game/drift-boss',
    tags: ['action', 'arcade', 'casual', 'hypercasual'],
    play_count: 0,
  },
]

export const getGameById = (gameId: string): GameItem | undefined => {
  return GAMES_DATA.find((game) => game.id === gameId)
}

export const getGamesByCategory = (category: string): GameItem[] => {
  return GAMES_DATA.filter((game) => game.category === category)
}
